function Gui(obj)
%% initialize
%Sets base properties for the gui
SAWin=obj.fig;
set(SAWin,'Name','Stock Analysis')
set(SAWin,'Units', 'normalized')
set(SAWin,'Position',[0.1,0.1,.7,.8])
set(SAWin,'ToolBar','none')
set(SAWin,'Resize','off')
set(SAWin,'SelectionType','open');
set(SAWin,'MenuBar','none');

%% Title Box Panel
%Sets the top right information box
Portfolio = uipanel('Parent',SAWin,...
    'Units', 'normalized',...
    'Position',[0,0.7,.3,.3]);

% Project title text
Project_title = uicontrol('Parent',Portfolio,...
    'Style','text',...
    'Units','normalized',...
    'Position',[0.1,0.65,0.8,0.3],...
    'HorizontalAlignment','center',...
    'FontSize',20,...
    'String','Investment Tools: Stock Charting');%#ok<NASGU>

% Member names text
Member_names = uicontrol('Parent',Portfolio,...
    'Style','text',...
    'Units','normalized',...
    'Position',[0.05,0.425,0.9,.15],...
    'HorizontalAlignment','center',...
    'FontSize',14,...
    'String','Brian Graf & Alex Hayashi'); %#ok<NASGU>

% Class info text
Class_info = uicontrol('Parent',Portfolio,...
    'Style','text',...
    'Units','normalized',...
    'Position',[0.05,0.3,0.9,.125],...
    'HorizontalAlignment','center',...
    'FontSize',14,...
    'String','E177 - Spring 2013');%#ok<NASGU>

% Bank title text
Banker = uicontrol('Parent',Portfolio,...
    'Style','text',...
    'Units','normalized',...
    'Position',[.05,0.15,0.5,0.15],...
    'FontSize',14,...
    'String','Bank Amount:');%#ok<NASGU>

% Portfolio value title text
PortVal = uicontrol('Parent',Portfolio,...
    'Style','text',...
    'Units','normalized',...
    'Position',[.05,0.075,0.5,0.1],...
    'FontSize',14,...
    'String','Portfolio Value:');%#ok<NASGU>

% Bank value text
BankTotal = uicontrol('Parent',Portfolio,...
    'Style','text',...
    'Units','normalized',...
    'Position',[0.5,0.15,0.45,0.15],...
    'FontSize',14,...
    'String',sprintf('%.2f',obj.portfolio.Bank));
value=0;
for i=1:length(obj.portfolio.PortfolioList)
    ticker=obj.portfolio.PortfolioList(i).Ticker;
    price=Stock.getStockInfo(ticker);
    value=value+price{2}.*obj.portfolio.PortfolioList(i).Shares;
end
% Bank value text
PortValTotal = uicontrol('Parent',Portfolio,...
    'Style','text',...
    'Units','normalized',...
    'Position',[0.5,0.075,0.45,0.1],...
    'FontSize',14,...
    'String',sprintf('%.2f',value));

%% Tabs
%Initializes the tabs and their text labels
tabs = uipanel('Parent',SAWin,...
    'Units', 'normalized',...
    'Position',[0,0.0,.3,.7]);

selectedTabColor=[0.59 0.73 0.87];
unselectedTabColor=get(tabs,'BackgroundColor');

tablabel1= axes('Parent',tabs,...
    'Units','normalized',...
    'Box','on',...
    'XTick',[],...
    'YTick',[],...
    'Color',selectedTabColor,...
    'Position',[0,0.95,.33,.05]);

tabtext1=text('String','Stock List',...
    'Units','normalized',...
    'Position',[0.5,0.5],...
    'HorizontalAlignment','center',...
    'VerticalAlignment','middle',...
    'Margin',0.001,...
    'FontSize',14);
tablabel2= axes('Parent',tabs,...
    'Units','normalized',...
    'Box','on',...
    'XTick',[],...
    'YTick',[],...
    'Color',unselectedTabColor,...
    'Position',[0.33,0.95,.33,.05]);
tabtext2=text('String','Watch List',...
    'Units','normalized',...
    'Position',[0.5,0.5],...
    'HorizontalAlignment','center',...
    'VerticalAlignment','middle',...
    'Margin',0.001,...
    'FontSize',14);
tablabel3= axes('Parent',tabs,...
    'Units','normalized',...
    'Box','on',...
    'XTick',[],...
    'YTick',[],...
    'Color',unselectedTabColor,...
    'Position',[0.66,0.95,.34,.05]);

tabtext3=text('String','Portfolio',...
    'Units','normalized',...
    'Position',[0.5,0.5],...
    'HorizontalAlignment','center',...
    'VerticalAlignment','middle',...
    'Margin',0.001,...
    'FontSize',14);
%% Search panel
%Creates the search panel and intializes the dynamic search box
Search=uipanel('Parent',tabs,...
    'Units','normalized',...
    'Position',[0,0,1,.95]);


searchbox=uicontrol(Search,'Style','edit',...
    'Units','normalized',...
    'BackgroundColor','white',...
    'Position',[0,.95,.7,.05]);

set(searchbox,'Units','pixels')
jedit  = java(findjobj(searchbox));
jedit_h = handle(jedit,'CallbackProperties');
set(searchbox,'KeyPressFcn',{@KPF_CB,jedit_h ,[],obj.fig,obj.StockLists{3}})
set(jedit_h ,'MouseReleasedCallback',{@KPF_MR_CB,searchbox}, ...
    'MousePressedCallback',{@KPF_MP_CB,searchbox});


%% Plot panels
% Panel for the price plotting
price_Panel = uipanel('Parent',SAWin,...
    'Units', 'normalized',...
    'Position',[0.3,0.45,.7,.55]);

% Panel for the user inputs to plotting
tools_Panel = uipanel('Parent',SAWin,...
    'Units', 'normalized',...
    'Position',[0.3,0,.7,.25]);

% Panel for the volume
volume_Panel = uipanel('Parent',SAWin,...
    'Units', 'normalized',...
    'Visible','on',...
    'Position',[0.3,.25,.7,.2]);

% Panel for the ticker info
info_Panel = uipanel('Parent',SAWin,...
    'Units', 'normalized',...
    'Visible','off',...
    'Position',[0.3,.25,.7,.2]);
%% Graph Axes Layout

% Price plot axes
Price_axes = axes('Parent',price_Panel,...
    'Units', 'normalized',...
    'Position',[.05, .05, .925, .815]);

% Stock Ticker and Company Name
Stock_label = uicontrol('Parent',price_Panel,...
    'Style', 'text',...
    'Units','normalized',...
    'Position',[.05, .875, .9, .1],...
    'FontSize',18,...
    'FontName','arial',...
    'HorizontalAlignment','center',...
    'String','Ticker - Company Name');

% Volume plot axes
Volume_axes = axes('Parent',volume_Panel,...
    'Units', 'normalized',...
    'Position',[.05, .145, .925, .68]);

%% Info Displays (initially hidden) - Pricing

% Open Price text box
open_text = uicontrol('Parent',info_Panel,...
    'Style', 'text',...
    'Units', 'normalized',...
    'Position',[.075,.725,.1,.125],...
    'FontSize',12,...
    'FontName','arial',...
    'HorizontalAlignment','center',...
    'Backgroundcolor','white',...
    'String','##');

% Open Price text label
open_text_label = uicontrol('Parent',info_Panel,...
    'Style', 'text',...
    'Units', 'normalized',...
    'Position',[.2,.725,.15,.125],...
    'FontSize',12,...
    'FontName','arial',...
    'HorizontalAlignment','left',...
    'String','Open Day Price');%#ok<NASGU>

% 52 week high text box
year_high_text = uicontrol('Parent',info_Panel,...
    'Style', 'text',...
    'Units', 'normalized',...
    'Position',[.075,.45,.1,.125],...
    'FontSize',12,...
    'HorizontalAlignment','center',...
    'Backgroundcolor','white',...
    'String','##');

% 52 week high text label
year_high_text_label = uicontrol('Parent',info_Panel,...
    'Style', 'text',...
    'Units', 'normalized',...
    'Position',[.2,.45,.15,.125],...
    'FontSize',12,...
    'HorizontalAlignment','left',...
    'String','52 Week High');%#ok<NASGU>

% 52 week low text box
year_low_text = uicontrol('Parent',info_Panel,...
    'Style', 'text',...
    'Units', 'normalized',...
    'Position',[.075,.175,.1,.125],...
    'FontSize',12,...
    'HorizontalAlignment','center',...
    'Backgroundcolor','white',...
    'String','##');

% 52 week high text label
year_low_text_label = uicontrol('Parent',info_Panel,...
    'Style', 'text',...
    'Units', 'normalized',...
    'Position',[.2,.175,.15,.125],...
    'FontSize',12,...
    'FontWeight','light',...
    'HorizontalAlignment','left',...
    'String','52 Week Low');%#ok<NASGU>
%% Info Displays (initially hidden) - Industry

% Market Cap text box
market_cap_text = uicontrol('Parent',info_Panel,...
    'Style', 'text',...
    'Units', 'normalized',...
    'Position',[.375,.725,.1,.125],...
    'FontSize',12,...
    'FontName','arial',...
    'HorizontalAlignment','center',...
    'Backgroundcolor','white',...
    'String','##');

% Market Cap text label
market_cap_text_label = uicontrol('Parent',info_Panel,...
    'Style', 'text',...
    'Units', 'normalized',...
    'Position',[.5,.725,.15,.125],...
    'FontSize',12,...
    'FontName','arial',...
    'HorizontalAlignment','left',...
    'String','Market Cap');%#ok<NASGU>

% P/E Ratio text box
pe_ratio_text = uicontrol('Parent',info_Panel,...
    'Style', 'text',...
    'Units', 'normalized',...
    'Position',[.375,.45,.1,.125],...
    'FontSize',12,...
    'HorizontalAlignment','center',...
    'Backgroundcolor','white',...
    'String','##');

% P/E Ratio text label
pe_ratio_text_label = uicontrol('Parent',info_Panel,...
    'Style', 'text',...
    'Units', 'normalized',...
    'Position',[.5,.45,.15,.125],...
    'FontSize',12,...
    'HorizontalAlignment','left',...
    'String','P/E Ratio');%#ok<NASGU>

% Price/Book text box
price_book_text = uicontrol('Parent',info_Panel,...
    'Style', 'text',...
    'Units', 'normalized',...
    'Position',[.375,.175,.1,.125],...
    'FontSize',12,...
    'HorizontalAlignment','center',...
    'Backgroundcolor','white',...
    'String','##');

% Price/Book text label
price_book_text_label = uicontrol('Parent',info_Panel,...
    'Style', 'text',...
    'Units', 'normalized',...
    'Position',[.5,.175,.15,.125],...
    'FontSize',12,...
    'FontWeight','light',...
    'HorizontalAlignment','left',...
    'String','Price/Book Ratio');%#ok<NASGU>
%% Info Displays (initially hidden) - Dividend/Volume

% Average Volume text box
avg_vol_text = uicontrol('Parent',info_Panel,...
    'Style', 'text',...
    'Units', 'normalized',...
    'Position',[.635,.725,.14,.125],...
    'FontSize',12,...
    'FontName','arial',...
    'HorizontalAlignment','center',...
    'Backgroundcolor','white',...
    'String','##');

% Average Volume text label
avg_vol_text_label = uicontrol('Parent',info_Panel,...
    'Style', 'text',...
    'Units', 'normalized',...
    'Position',[.8,.725,.15,.125],...
    'FontSize',12,...
    'FontName','arial',...
    'HorizontalAlignment','left',...
    'String','Average Volume');%#ok<NASGU>

% Dividend per Share text box
dividend_text = uicontrol('Parent',info_Panel,...
    'Style', 'text',...
    'Units', 'normalized',...
    'Position',[.665,.45,.11,.125],...
    'FontSize',12,...
    'HorizontalAlignment','center',...
    'Backgroundcolor','white',...
    'String','##');

% Dividend per Share text label
dividend_text_label = uicontrol('Parent',info_Panel,...
    'Style', 'text',...
    'Units', 'normalized',...
    'Position',[.8,.45,.15,.125],...
    'FontSize',12,...
    'HorizontalAlignment','left',...
    'String','Dividend/Share');%#ok<NASGU>

% Dividend Date text box
div_date_text = uicontrol('Parent',info_Panel,...
    'Style', 'text',...
    'Units', 'normalized',...
    'Position',[.665,.175,.11,.125],...
    'FontSize',12,...
    'HorizontalAlignment','center',...
    'Backgroundcolor','white',...
    'String','##');

% Dividend Date text label
div_date_text_label = uicontrol('Parent',info_Panel,...
    'Style', 'text',...
    'Units', 'normalized',...
    'Position',[.8,.175,.15,.125],...
    'FontSize',12,...
    'FontWeight','light',...
    'HorizontalAlignment','left',...
    'String','Dividend Date');%#ok<NASGU>

%% Scaling and Other Checkbox Options

% X-axis scaling text
xaxis_text = uicontrol('Parent',tools_Panel,...
    'Style', 'text',...
    'Units', 'normalized',...
    'Position',[.025,.77,.2,.15],...
    'FontSize',12,...
    'FontName','arial',...
    'HorizontalAlignment','left',...
    'FontWeight','normal',...
    'String','Specify Time Period');%#ok<NASGU>

% X axis scaling pop up menu
xaxis_popup = uicontrol('Parent',tools_Panel,...
    'Style', 'popupmenu',...
    'Units', 'normalized',...
    'Position',[.025,.67,.2,.15],...
    'FontSize',12,...
    'String', {'1 Week','2 Weeks','1 Month','3 Months','6 Months','1 Year','2 Years'},...
    'Backgroundcolor','white',...
    'Value',4,...
    'Callback',{@xaxis_time_selection,obj});

% Create a uibuttongroup to switch between volume and ticker info
plot_switch = uibuttongroup('Parent',tools_Panel,...
    'Units', 'normalized',...
    'Position',[0.04,0.125,.175,.41],...
    'Title','More Information',...
    'FontSize',12,...
    'SelectionChangeFcn',{@hide_on_off,obj});

% Volume Plot on/off radio buttongroup
radio{1} = uicontrol('Parent',plot_switch,...
    'Style', 'radio',...
    'Units', 'normalized',...
    'Position',[.025,.55,.8,.4],...
    'FontSize',12,...
    'String', 'Volume Plot',...
    'Value', 1);

% Ticker Info on/off radio buttongroup
radio{2} = uicontrol('Parent',plot_switch,...
    'Style', 'radio',...
    'Units', 'normalized',...
    'Position',[.025,.075,.8,.4],...
    'FontSize',12,...
    'String', 'Stock Info',...
    'Value', 0);

    function hide_on_off(~,~,obj)
        if get(radio{1},'Value') == 1
            % turn visibility of info panel off
            set(info_Panel,'Visible','off');
            set(volume_Panel,'Visible','on');
        else
            % turn visibility of info panel on
            set(volume_Panel,'Visible','off');
            set(info_Panel,'Visible','on');
            Panel_stock = Stock(obj.current_ticker,analysisHandle);
            extra_info(Panel_stock)
        end
    end

%% Simple Moving Average and Offset

% Simple Moving Average (SMA) checkbox
SMA_checkbox = uicontrol('Parent',tools_Panel,...
    'Style', 'checkbox',...
    'Units', 'normalized',...
    'Position',[.255,.75,.25,.15],...
    'FontSize',12,...
    'String', 'Simple Moving Average',...
    'Value',0,...
    'Callback',{@SMA_inter,obj});

% SMA number of days edit
SMA_days_edit = uicontrol('Parent',tools_Panel,...
    'Style', 'edit',...
    'Units', 'normalized',...
    'Position',[.255,.5,.05,.15],...
    'FontSize',12,...
    'Backgroundcolor','white',...
    'Value',50,...
    'CallBack',{@SMA_inter,obj});

% SMA number of days text
SMA_days_text = uicontrol('Parent',tools_Panel,...
    'Style', 'text',...
    'Units', 'normalized',...
    'Position',[.31,.48,.2,.15],...
    'FontSize',12,...
    'FontName','arial',...
    'HorizontalAlignment','left',...
    'String','Specify Days of SMA');%#ok<NASGU>

% Simple Moving Average Offset checkbox
SMA_offset_checkbox = uicontrol('Parent',tools_Panel,...
    'Style', 'checkbox',...
    'Units', 'normalized',...
    'Position',[.255,.27,.2,.15],...
    'FontSize',12,...
    'String', 'SMA Offset',...
    'Value',0,...
    'Callback',{@SMA_offset_inter,obj});

% SMA number of days edit
SMA_offset_edit = uicontrol('Parent',tools_Panel,...
    'Style', 'edit',...
    'Units', 'normalized',...
    'Position',[.255,.07,.05,.15],...
    'FontSize',12,...
    'Backgroundcolor','white',...
    'Value',50,...
    'Callback',{@SMA_offset_inter,obj});

% SMA number of days text
SMA_offset_text = uicontrol('Parent',tools_Panel,...
    'Style', 'text',...
    'Units', 'normalized',...
    'Position',[.31,.04,.2,.15],...
    'FontSize',12,...
    'FontName','arial',...
    'HorizontalAlignment','left',...
    'String','Specify Offset %');%#ok<NASGU>

%% Exponential Moving Average and Offset

% Exponential Moving Average (EMA) checkbox
EMA_checkbox = uicontrol('Parent',tools_Panel,...
    'Style', 'checkbox',...
    'Units', 'normalized',...
    'Position',[.525,.75,.25,.15],...
    'FontSize',12,...
    'String', 'Exponential Moving Avg.',...
    'Value',0,...
    'Callback',{@EMA_inter,obj});

% EMA number of days edit
EMA_days_edit = uicontrol('Parent',tools_Panel,...
    'Style', 'edit',...
    'Units', 'normalized',...
    'Position',[.525,.5,.05,.15],...
    'FontSize',12,...
    'Backgroundcolor','white',...
    'Value',50,...
    'Callback',{@EMA_inter,obj});

% EMA number of days text
EMA_days_text = uicontrol('Parent',tools_Panel,...
    'Style', 'text',...
    'Units', 'normalized',...
    'Position',[.58,.48,.2,.15],...
    'FontSize',12,...
    'FontName','arial',...
    'HorizontalAlignment','left',...
    'String','Specify Days of EMA');%#ok<NASGU>

% Exponential Moving Average Offset checkbox
EMA_offset_checkbox = uicontrol('Parent',tools_Panel,...
    'Style', 'checkbox',...
    'Units', 'normalized',...
    'Position',[.525,.27,.2,.15],...
    'FontSize',12,...
    'String', 'EMA Offset',...
    'Value',0,...
    'Callback',{@EMA_offset_inter,obj});

% SMA number of days edit
EMA_offset_edit = uicontrol('Parent',tools_Panel,...
    'Style', 'edit',...
    'Units', 'normalized',...
    'Position',[.525,.07,.05,.15],...
    'FontSize',12,...
    'Backgroundcolor','white',...
    'Value',50,...
    'Callback',{@EMA_offset_inter,obj});

% SMA number of days text
EMA_offset_text = uicontrol('Parent',tools_Panel,...
    'Style', 'text',...
    'Units', 'normalized',...
    'Position',[.58,.04,.2,.15],...
    'FontSize',12,...
    'FontName','arial',...
    'HorizontalAlignment','left',...
    'String','Specify Offset %');%#ok<NASGU>

%% Trendlines

% Upper Trendline Checkbox
Trend_up_checkbox = uicontrol('Parent',tools_Panel,...
    'Style', 'checkbox',...
    'Units', 'normalized',...
    'Position',[.8,.75,.2,.15],...
    'FontSize',12,...
    'String', 'Upper Trendline',...
    'Value',0,...
    'Callback',{@Upper_trendline_inter,obj});

% Lower Trendline Checkbox
Trend_down_checkbox = uicontrol('Parent',tools_Panel,...
    'Style', 'checkbox',...
    'Units', 'normalized',...
    'Position',[.8,.52,.2,.15],...
    'FontSize',12,...
    'String', 'Lower Trendline',...
    'Value',0,...
    'Callback',{@Lower_trendline_inter,obj});

%% Volume Checks

% Volume max checkbox
volumemax_checkbox = uicontrol('Parent',tools_Panel,...
    'Style', 'checkbox',...
    'Units', 'normalized',...
    'Position',[.8,.27,.2,.15],...
    'FontSize',12,...
    'String', 'Show Max Vol.',...
    'Value',0,...
    'Callback',{@max_volume_inter,obj});


% Volume min checkbox
volumemin_checkbox = uicontrol('Parent',tools_Panel,...
    'Style', 'checkbox',...
    'Units', 'normalized',...
    'Position',[.8,.07,.2,.15],...
    'FontSize',12,...
    'String', 'Show Min Vol.',...
    'Value',0,...
    'Callback',{@min_volume_inter,obj});

% Cell array containing figure handles
analysisHandle={Price_axes,Volume_axes,info_Panel,tools_Panel,...
    xaxis_popup,SMA_checkbox,SMA_days_edit,SMA_offset_checkbox,...
    SMA_offset_edit,EMA_offset_checkbox,EMA_offset_edit,...
    Trend_up_checkbox,Trend_down_checkbox,volumemax_checkbox,...
    volumemin_checkbox,[],open_text,year_high_text,...
    year_low_text,market_cap_text,pe_ratio_text,price_book_text,...
    avg_vol_text,dividend_text,div_date_text,Stock_label,EMA_checkbox,...
    EMA_days_edit};

%% Watchlist panel
%Sets up the watchlist panel, the handles to the tiles and the uibuttons
Watchlist=uipanel('Parent',tabs,...
    'Units','normalized',...
    'Position',[0,0,1,.95],...
    'Visible','off');
size=[1,.095];

obj.pagewatch=1;


stockwatch=cell.empty(10,0);
tickerwatch=cell.empty(10,0);
namewatch=cell.empty(10,0);
pricewatch=cell.empty(10,0);
percentChangeWatch=cell.empty(10,0);
for i=1:10
    stockwatch{i}=axes('parent',Watchlist,...
        'Units','normalized',...
        'Position',[0,1-.09*i,size],...
        'Box','on',...
        'XTick',[],...
        'YTick',[]);
    tickerwatch{i}=text('parent',stockwatch{i},...
        'Units','normalized',...
        'Position',[0.1,0.7],...
        'HorizontalAlignment','left');
    namewatch{i}=text('parent',stockwatch{i},...
        'Units','normalized',...
        'Position',[0.3,.7],...
        'HorizontalAlignment','left');
    pricewatch{i}=text('parent',stockwatch{i},...
        'Units','normalized',...
        'HorizontalAlignment','left',...
        'Position',[0.8,.7]);
    percentChangeWatch{i}=text('parent',stockwatch{i},...
        'Units','normalized',...
        'HorizontalAlignment','left',...
        'Position',[0.1,.3]);
end
watchHandles={stockwatch,tickerwatch,namewatch,pricewatch,analysisHandle,percentChangeWatch};

PrevPageWatch=uicontrol(Watchlist,'style','pushbutton',...
    'Units','normalized',...
    'string','Prev Page',...
    'Position',[0,0,.25,.1]);

NextPageWatch=uicontrol(Watchlist,'style','pushbutton',...
    'Units','normalized',...
    'string','Next Page',...
    'Position',[0.25,0,.25,.1]);
pageButtonsWatch={PrevPageWatch,NextPageWatch};
remove=uicontrol(Watchlist,'style','pushbutton',...
    'Units','normalized',...
    'string','Remove',...
    'Position',[0.50,0,.25,.1],...
    'callback',{@removeStock,watchHandles,obj,pageButtonsWatch});%#ok<NASGU>
Buystock=uicontrol(Watchlist,'style','pushbutton',...
    'Units','normalized',...
    'string','Buy Stock',...
    'Position',[0.75,0,.25,.1],...
    'callback',{@purchaseStock,obj,BankTotal,PortValTotal});%#ok<NASGU>


%% Portfolio panel
%Sets up the portfolio panel, the handles to the tiles and the uibuttons
portfolio=uipanel('Parent',tabs,...
    'Units','normalized',...
    'Position',[0,0,1,.95],...
    'Visible','off');

obj.pageport=1;

stockport=cell.empty(10,0);
tickerport=cell.empty(10,0);
nameport=cell.empty(10,0);
priceport=cell.empty(10,0);
amount=cell.empty(10,0);
percentChangePort=cell.empty(10,0);
for i=1:10
    stockport{i}=axes('parent',portfolio,...
        'Units','normalized',...
        'Position',[0,1-.09*i,size],...
        'Box','on',...
        'XTick',[],...
        'YTick',[]);
    tickerport{i}=text('parent',stockport{i},...
        'Units','normalized',...
        'Position',[0.1,0.7],...
        'HorizontalAlignment','left');
    nameport{i}=text('parent',stockport{i},...
        'Units','normalized',...
        'Position',[0.3,.7],...
        'HorizontalAlignment','left');
    priceport{i}=text('parent',stockport{i},...
        'Units','normalized',...
        'HorizontalAlignment','left',...
        'Position',[0.8,.7]);
    amount{i}=text('parent',stockport{i},...
        'Units','normalized',...
        'HorizontalAlignment','left',...
        'Position',[0.1,.3]);
    percentChangePort{i}=text('parent',stockport{i},...
        'Units','normalized',...
        'HorizontalAlignment','left',...
        'Position',[0.7,.3]);
end

portHandles={stockport,tickerport,nameport,priceport,analysisHandle,percentChangePort,amount};

PrevPagePort=uicontrol(portfolio,'style','pushbutton',...
    'Units','normalized',...
    'string','Prev Page',...
    'Position',[0,0,.33,.1]);

NextPagePort=uicontrol(portfolio,'style','pushbutton',...
    'Units','normalized',...
    'string','Next Page',...
    'Position',[0.33,0,.33,.1]);

pageButtonsPort={PrevPagePort,NextPagePort};
Sell=uicontrol(portfolio,'style','pushbutton',...
    'Units','normalized',...
    'string','Sell Stock',...
    'Position',[0.66,0,.33,.1],...
    'callback',{@sellStock,obj,BankTotal,PortValTotal,portHandles,pageButtonsPort});%#ok<NASGU>



%% Tab controls
%Sets the callbacks that allow the tabs to call the pannels to make them
%visible
%Also sets the next and previous buttons on watchlist and portfolio
handles={Search,Watchlist,portfolio,tablabel1,tablabel2,tablabel3};
color={selectedTabColor,unselectedTabColor};
set(tablabel1,'ButtonDownFcn',{@tabAction1,handles,color});
set(tablabel2,'ButtonDownFcn',{@tabAction2,handles,color,watchHandles,obj,pageButtonsWatch});
set(tablabel3,'ButtonDownFcn',{@tabAction3,handles,color,portHandles,obj,pageButtonsPort});
set(tabtext1,'ButtonDownFcn',{@tabAction1,handles,color});
set(tabtext2,'ButtonDownFcn',{@tabAction2,handles,color,watchHandles,obj,pageButtonsWatch});
set(tabtext3,'ButtonDownFcn',{@tabAction3,handles,color,portHandles,obj,pageButtonsPort});

set(PrevPageWatch,'callback',{@prev,'watch',watchHandles,obj,pageButtonsWatch});
set(NextPageWatch,'callback',{@next,'watch',watchHandles,obj,pageButtonsWatch});
set(PrevPagePort,'callback',{@prev,'port',portHandles,obj,pageButtonsPort});
set(NextPagePort,'callback',{@next,'port',portHandles,obj,pageButtonsPort});

%% Watch Buttons
%Sets up the buttons for the search tab
watch=uicontrol(Search,'Style','pushbutton',...
    'Units','normalized',...
    'Position',[0.7,0.95,.3,.05],...
    'String','Watch Stock',...
    'callback',{@addWatch,searchbox,obj.StockLists,obj});%#ok<NASGU>
buy=uicontrol(Search,'Style','pushbutton',...
    'Units','normalized',...
    'Position',[0.7,0.9,.3,.05],...
    'String','Buy Stock',...
    'callback',{@buyStock,searchbox,obj,BankTotal,PortValTotal});%#ok<NASGU>
ana=uicontrol(Search,'Style','pushbutton',...
    'Units','normalized',...
    'Position',[0.7,0.85,.3,.05],...
    'String','Analyze Stock',...
    'callback',{@analyze,searchbox,analysisHandle,obj});%#ok<NASGU>

end

function tabAction1(~,~,handles,color)
%Makes the search tab active
set(handles{4},'Color',color{1})
set(handles{5},'Color',color{2})
set(handles{6},'Color',color{2})
set(handles{1},'Visible','on')
set(handles{2},'Visible','off')
set(handles{3},'Visible','off')
end

function tabAction2(~,~,handles,color,watchHandles,obj,button)
%Makes the watchlist tab active
set(handles{5},'Color',color{1})
set(handles{4},'Color',color{2})
set(handles{6},'Color',color{2})
set(handles{2},'Visible','on')
set(handles{1},'Visible','off')
set(handles{3},'Visible','off')
list=obj.watchlist.list;
poplist(obj.pagewatch,watchHandles,list,obj,button)

end

function tabAction3(~,~,handles,color,portHandles,obj,button)
%Makes the portfolio list tab active
set(handles{6},'Color',color{1})
set(handles{4},'Color',color{2})
set(handles{5},'Color',color{2})
set(handles{3},'Visible','on')
set(handles{2},'Visible','off')
set(handles{1},'Visible','off')
list=obj.portfolio.PortfolioList;
poplist(obj.pageport,portHandles,list,obj,button)

end

function addWatch(~,~,searchbox,list,obj)
%call back to add stock to watch list
stock=get(searchbox,'String');
ticker=findticker(stock,list);
obj.watchlist.addStock(ticker)
[~, ind]=sort({obj.watchlist.list.Ticker});
obj.watchlist.list=obj.watchlist.list(ind);
set(searchbox,'string',[]);

end

function buyStock(~,~,searchbox,obj,BankTotal,PortValTotal)
%Call back to buy stock
stock=get(searchbox,'String');
ticker=findticker(stock,obj.StockLists);
price=Stock.getStockInfo(ticker{1});
maxPurchase=floor(obj.portfolio.Bank/price{2});
str=sprintf('You have $ %.2f and can buy %.0f shares. \n How shares would you like to buy?',...
    obj.portfolio.Bank,maxPurchase);
prompt = {str};
dlg_title = sprintf('Buy %s Stock',ticker{1});
answer = inputdlg(prompt,dlg_title,[1 50]);
obj.portfolio.buyStock(ticker{1},str2double(answer{1}))

value=0;
for i=1:length(obj.portfolio.PortfolioList)
    ticker=obj.portfolio.PortfolioList(i).Ticker;
    price=Stock.getStockInfo(ticker);
    value=value+price{2}.*obj.portfolio.PortfolioList(i).Shares;
end
set(PortValTotal,'String',sprintf('%.2f',value));
set(BankTotal,'String',sprintf('%.2f',obj.portfolio.Bank));
[~, ind]=sort({obj.portfolio.PortfolioList.Ticker});
obj.portfolio.PortfolioList=obj.portfolio.PortfolioList(ind);
set(searchbox,'string',[]);
end

function poplist(page,handles,list,obj,button)
%Populates the list of the watchlist or portfolio
lastpage=ceil(length(list)/10);

if page==lastpage |lastpage==0
    set(button{2},'enable','off')
else
    set(button{2},'enable','on')
end
if page<=1
    set(button{1},'enable','off')
else
    set(button{1},'enable','on')
end

if lastpage==1
    if length(list)<10
        for i=1:length(list)
            temp=Stock.getStockInfo(list(i).Ticker);
            set(handles{1}{i},'ButtonDownFcn',{@analysis,list(i).Ticker,handles{5},obj});%
            set(handles{2}{i},'ButtonDownFcn',{@analysis,list(i).Ticker,handles{5},obj})
            set(handles{3}{i},'ButtonDownFcn',{@analysis,list(i).Ticker,handles{5},obj})
            set(handles{4}{i},'ButtonDownFcn',{@analysis,list(i).Ticker,handles{5},obj})
            set(handles{2}{i},'string',list(i).Ticker);
            set(handles{3}{i},'string',temp{1}{1})
            set(handles{4}{i},'string',sprintf('%.2f',temp{2}));
            set(handles{6}{i},'ButtonDownFcn',{@analysis,list(i).Ticker,handles{5},obj})
            set(handles{6}{i},'string',temp{3}{1});
            if length(handles)>6
                set(handles{7}{i},'ButtonDownFcn',{@analysis,list(i).Ticker,handles{5},obj})
                set(handles{7}{i},'string',['Shares: ' num2str(list(i).Shares)]);
                
            end
        end
        for i=length(list)+1:10
            set(handles{1}{i},'ButtonDownFcn',{})
            set(handles{2}{i},'string',[]);
            set(handles{3}{i},'string',[]);
            set(handles{4}{i},'string',[]);
            set(handles{6}{i},'string',[]);
            if length(handles)>6
                set(handles{7}{i},'string',[]);
                
            end
        end
    else
        for i=1:10
            temp=Stock.getStockInfo(list(i).Ticker);
            set(handles{1}{i},'ButtonDownFcn',{@analysis,list(i).Ticker,handles{5},obj})
            set(handles{2}{i},'ButtonDownFcn',{@analysis,list(i).Ticker,handles{5},obj})
            set(handles{3}{i},'ButtonDownFcn',{@analysis,list(i).Ticker,handles{5},obj})
            set(handles{4}{i},'ButtonDownFcn',{@analysis,list(i).Ticker,handles{5},obj})
            set(handles{2}{i},'string',list(i).Ticker);
            set(handles{3}{i},'string',temp{1}{1})
            set(handles{4}{i},'string',sprintf('%.2f',temp{2}));
            set(handles{6}{i},'ButtonDownFcn',{@analysis,list(i).Ticker,handles{5},obj})
            set(handles{6}{i},'string',temp{3}{1});
            if length(handles)>6
                set(handles{7}{i},'ButtonDownFcn',{@analysis,list(i).Ticker,handles{5},obj})
                set(handles{7}{i},'string',['Shares: ' num2str(list(i).Shares)]);
                
            end
        end
    end
else
    if length(list)-(page-1)*10<10
        for i=1:length(list)-(page-1)*10
            n=i+(page-1)*10;
            temp=Stock.getStockInfo(list(n).Ticker);
            set(handles{1}{i},'ButtonDownFcn',{@analysis,list(i).Ticker,handles{5},obj})
            set(handles{2}{i},'ButtonDownFcn',{@analysis,list(i).Ticker,handles{5},obj})
            set(handles{3}{i},'ButtonDownFcn',{@analysis,list(i).Ticker,handles{5},obj})
            set(handles{4}{i},'ButtonDownFcn',{@analysis,list(i).Ticker,handles{5},obj})
            set(handles{2}{i},'string',list(n).Ticker);
            set(handles{3}{i},'string',temp{1}{1})
            set(handles{4}{i},'string',sprintf('%.2f',temp{2}));
            set(handles{6}{i},'ButtonDownFcn',{@analysis,list(i).Ticker,handles{5},obj})
            set(handles{6}{i},'string',temp{3}{1});
            if length(handles)>6
                set(handles{7}{i},'ButtonDownFcn',{@analysis,list(i).Ticker,handles{5},obj})
                set(handles{7}{i},'string',['Shares: ' num2str(list(i).Shares)]);
                
            end
        end
        for i=(length(list)-(page-1)*10)+1:10
            set(handles{1}{i},'ButtonDownFcn',{})
            set(handles{2}{i},'string',[]);
            set(handles{3}{i},'string',[]);
            set(handles{4}{i},'string',[]);
            set(handles{6}{i},'string',[]);
            if length(handles)>6
                set(handles{7}{i},'string',[]);
                
            end
        end
    else
        for i=1:10
            n=i+(page-1)*10;
            temp=Stock.getStockInfo(list(n).Ticker);
            
            set(handles{1}{i},'ButtonDownFcn',{@analysis,list(i).Ticker,handles{5},obj})
            set(handles{2}{i},'ButtonDownFcn',{@analysis,list(i).Ticker,handles{5},obj})
            set(handles{3}{i},'ButtonDownFcn',{@analysis,list(i).Ticker,handles{5},obj})
            set(handles{4}{i},'ButtonDownFcn',{@analysis,list(i).Ticker,handles{5},obj})
            set(handles{2}{i},'string',list(n).Ticker);
            set(handles{3}{i},'string',temp{1}{1})
            set(handles{4}{i},'string',sprintf('%.2f',temp{2}));
            set(handles{6}{i},'ButtonDownFcn',{@analysis,list(i).Ticker,handles{5},obj})
            set(handles{6}{i},'string',temp{3}{1});
            if length(handles)>6
                set(handles{7}{i},'ButtonDownFcn',{@analysis,list(i).Ticker,handles{5},obj})
                set(handles{7}{i},'string',['Shares: ' num2str(list(i).Shares)]);
                
            end
        end
    end
end
end

function prev(~,~,style,watchHandles,obj,Buttons)
%call back for previous button
if strcmp(style,'port')
    obj.pageport=obj.pageport-1;
    page= obj.pageport;
    list=obj.portfolio.PortfolioList;
else
    obj.pagewatch=obj.pagewatch-1;
    page= obj.pagewatch;
    list=obj.watchlist.list;
end

poplist(page,watchHandles,list,obj,Buttons);
end

function next(~,~,style,watchHandles,obj,Buttons)
%call back for next button
if strcmp(style,'port')
    obj.pageport=obj.pageport+1;
    page= obj.pageport;
    list=obj.portfolio.PortfolioList;
else
    obj.pagewatch=obj.pagewatch+1;
    list=obj.watchlist.list;
    page= obj.pagewatch;
end
poplist(page,watchHandles,list,obj,Buttons);
end

function analysis(~,~,ticker,CellHandles,obj)
%Launches the analaysis of the stock
obj.analysis=Analysis(ticker,CellHandles);
obj.current_ticker = ticker;
end

function removeStock(~,~,Handles,obj,Buttons)
%Removes stock from watchlist
obj.watchlist.removeStock(obj.current_ticker)
poplist(obj.pagewatch,Handles,obj.watchlist.list,obj,Buttons);
end

function sellStock(~,~,obj,BankTotal,PortValTotal,Handles,Buttons)
%Sells stock from portfolio
ticker=obj.current_ticker;
i=1;
while i<=length(obj.portfolio.PortfolioList)
    if strcmp(ticker,obj.portfolio.PortfolioList(i).Ticker)
        amount=obj.portfolio.PortfolioList(i).Shares;
    end
    i=i+1;
end
valid=0;
while valid==0
    prompt = {sprintf('Own %d shares. How many would you like to sell?',amount)};
    dlg_title = sprintf('Sell %s Stock',ticker);
    answer = inputdlg(prompt,dlg_title);
    if ~isempty(answer)
        selling=str2double(answer{1});
        if selling>amount
            errorbox=msgbox(['You do not own enough shares to sell' answer{1}],'Error','error');
            waitfor(errorbox)
        else
            valid=1;
            obj.portfolio.sellStock(ticker,selling);
        end
    else
        valid=1;
    end
end


value=0;
for j=1:length(obj.portfolio.PortfolioList)
    ticker=obj.portfolio.PortfolioList(j).Ticker;
    price=Stock.getStockInfo(ticker);
    value=value+price{2}.*obj.portfolio.PortfolioList(j).Shares;
end
set(PortValTotal,'String',sprintf('%.2f',value));
set(BankTotal,'String',sprintf('%.2f',obj.portfolio.Bank));
poplist(obj.pageport,Handles,obj.portfolio.PortfolioList,obj,Buttons);
end

function ticker=findticker(stock,list)
loc=find(strcmp([list{3}],stock));
x=length(list{1});
if loc>x
    loc=loc-x;
    ticker=list{1}(loc);
else
    ticker=list{1}(loc);
end
end

function Lower_trendline_inter(~,~,obj)
obj.analysis.Lower_trendline()
end

function Upper_trendline_inter(~,~,obj)
obj.analysis.Upper_trendline()
end

function min_volume_inter(~,~,obj)
obj.analysis.Min_volume()
end

function max_volume_inter(~,~,obj)
obj.analysis.Max_volume()
end

function SMA_inter(~,~,obj)
obj.analysis.SMA()
end

function SMA_offset_inter(~,~,obj)
obj.analysis.SMA_offset()
end

function EMA_inter(~,~,obj)
obj.analysis.EMA()
end

function EMA_offset_inter(~,~,obj)
obj.analysis.EMA_offset()
end

function xaxis_time_selection(~,~,obj)
obj.analysis.scale_xaxis()
end
function analyze(~,~,searchbox,handles,obj)
%call back for analyzing from search box
stock=get(searchbox,'String');
ticker=findticker(stock,obj.StockLists);
obj.analysis=Analysis(ticker{1},handles);
set(searchbox,'string',[]);
end
function purchaseStock(~,~,obj,BankTotal,PortValTotal)
%Call back to buy stock from watchlist

price=Stock.getStockInfo(obj.current_ticker);
maxPurchase=floor(obj.portfolio.Bank/price{2});
str=sprintf('You have $ %.2f and can buy %.0f shares. \n How shares would you like to buy?',...
    obj.portfolio.Bank,maxPurchase);
prompt = {str};
dlg_title = sprintf('Buy %s Stock',obj.current_ticker);
answer = inputdlg(prompt,dlg_title,[1 50]);
obj.portfolio.buyStock(obj.current_ticker,str2double(answer{1}))

value=0;
for i=1:length(obj.portfolio.PortfolioList)
    ticker=obj.portfolio.PortfolioList(i).Ticker;
    price=Stock.getStockInfo(ticker);
    value=value+price{2}.*obj.portfolio.PortfolioList(i).Shares;
end
set(PortValTotal,'String',sprintf('%.2f',value));
set(BankTotal,'String',sprintf('%.2f',obj.portfolio.Bank));
[~, ind]=sort({obj.portfolio.PortfolioList.Ticker});
obj.portfolio.PortfolioList=obj.portfolio.PortfolioList(ind);
end

